name: fluxo_caixa_familiar
description: Sistema de Gerenciamento Financeiro Familiar

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Localização
  flutter_localizations:
    sdk: flutter
  
  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.0
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.8.3
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Date & Time
  intl: ^0.19.0
  
  # Charts & Analytics
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^29.1.38
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Math & Statistics
  collection: ^1.17.2
  
  # Image & Camera
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  
  # OCR & Text Recognition
  google_mlkit_text_recognition: ^0.11.0
  google_mlkit_commons: ^0.6.0
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # Utils
  uuid: ^4.3.3
  crypto: ^3.0.3
  permission_handler: ^11.3.0
  shimmer: ^3.0.0
  
  # Biometric Authentication
  local_auth: ^2.3.0
  
  # Firebase dependencies removed to fix build issues
  # firebase_core: ^2.24.2
  # cloud_firestore: ^4.13.6
  # firebase_auth: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.1
  build_runner: ^2.4.7
  test: ^1.24.9
  sqflite_common_ffi: ^2.3.2
  
  # Coverage
  coverage: ^1.7.2
  
  # Icon Generation
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  web: ^1.0.0

flutter:
  uses-material-design: true

# Configuração dos ícones do app
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#3F51B5"
    theme_color: "#3F51B5"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
