// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCfBPAxf9hLD73oURVO__8fkZRATv8D-g',
    appId: '1:149560957094:web:your-web-app-id',
    messagingSenderId: '149560957094',
    projectId: 'familycashflow-1e994',
    authDomain: 'familycashflow-1e994.firebaseapp.com',
    storageBucket: 'familycashflow-1e994.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCfBPAxf9hLD73oURVO__8fkZRATv8D-g',
    appId: '1:149560957094:android:eedf5ae4bc66ec611f3c67',
    messagingSenderId: '149560957094',
    projectId: 'familycashflow-1e994',
    storageBucket: 'familycashflow-1e994.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCfBPAxf9hLD73oURVO__8fkZRATv8D-g',
    appId: '1:149560957094:ios:your-ios-app-id',
    messagingSenderId: '149560957094',
    projectId: 'familycashflow-1e994',
    storageBucket: 'familycashflow-1e994.firebasestorage.app',
    iosBundleId: 'com.example.fluxoCaixaFamiliar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCfBPAxf9hLD73oURVO__8fkZRATv8D-g',
    appId: '1:149560957094:ios:your-macos-app-id',
    messagingSenderId: '149560957094',
    projectId: 'familycashflow-1e994',
    storageBucket: 'familycashflow-1e994.firebasestorage.app',
    iosBundleId: 'com.example.fluxoCaixaFamiliar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCfBPAxf9hLD73oURVO__8fkZRATv8D-g',
    appId: '1:149560957094:web:your-windows-app-id',
    messagingSenderId: '149560957094',
    projectId: 'familycashflow-1e994',
    authDomain: 'familycashflow-1e994.firebaseapp.com',
    storageBucket: 'familycashflow-1e994.firebasestorage.app',
  );
}
